### ISSUE TITLE
FastPitch: The inference is incredibly slow even when using GPU

### ISSUE THREAD

**Issue by marzieh-razavi** [NVIDIA/DeepLearningExamples#1179]
Hello, I am using the FastPitch along with the HiFi-GAN as the vocoder using GPU. The training is done quite fast using multiple gpus, however, the inference is incredibly slow. It is taking hours to generate audio files when using a single GPU. I have set the 
cuda and cudnn-benchmark arguments to true, and torchscript and torch_tensorrt arguments to false. I would be really grateful if you could help me with this issue. When i use nvidia-smi, it actually shows that the GPU is occupied, however, Volatile GPU util is 0%:
|   9  NVIDIA RTX A6000    Off  | 00000000:CC:00.0 Off |                  Off |
| 30%   31C    P8    26W / 300W |   1845MiB / 49140MiB |      0%      Default

**Comment by marzieh-razavi** [comment]
The issue was resolved by adding the following command:
export OMP_NUM_THREADS=1

**Comment by ngocpham97** [comment]
I have same problem when use GPU, the first time when inference a new sample so slowly. I try export OMP_NUM_THREADS=1
but  the problem is not solved. Do you have any ideas ?
