### ISSUE TITLE
float16 model in the Fastertransformer/sample/tensorflow_bert can't run 

### ISSUE THREAD

**Issue by zhoushan2186new** [NVIDIA/DeepLearningExamples#257]
We have successfully built and run all the sample in faster transformer except for the sample/tensorflow_bert in float16 mode. It runs ok with float32 mode and the converting from fp32 to fp16 also succeed. Here are the steps:
1. RUN BERT in fp32 works. 
python run_classifier_wrap.py --data_dir=/path/glue_data//MRPC --task_name=MRPC --vocab_file=/path/vocab.txt --bert_config_file=/path/bert_config.json --output_dir=mrpc_output --floatx=float32 --do_predict=true --init_checkpoint=/path/model.ckpt-343
2. convert fp32 to fp16 works.
python ckpt_type_convert.py --init_checkpoint=/path/model.ckpt-343 --fp16_checkpoint=path/fp16_model.ckpt
3. It fails to run in fp16 mode. 
python run_classifier_wrap.py --data_dir=/path/glue_data//MRPC --task_name=MRPC --vocab_file=/path/vocab.txt --bert_config_file=/path/bert_config.json --output_dir=mrpc_output --floatx=float16 --do_predict=true --init_checkpoint=/path/fp16_model.ckpt
The error shows below:
2019-10-15 07:47:34.036893: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at bert_transformer_op.cc:164 : Internal: [FT][ERROR] CUDA runtime error: CUBLAS_STATUS_NOT_SUPPORTED /work/test/nv-bert/DeepLearningExamples/FasterTransformer/fastertransformer/cuda/open_attention.h:171

**Comment by zhoushan2186new** [comment]
And the CUDA runtime version is cuda10.1

**Comment by dontloo** [comment]
@zhoushan2186new hi did you run the algorithm selection script for fp16 before running? https://github.com/NVIDIA/DeepLearningExamples/tree/master/FasterTransformer#execute-demos

`./build/bin/gemm_fp16(32) <batch_size> <seq_len> <head_num> <size_per_head>`

**Comment by zhoushan2186new** [comment]
@dontloo
Hi, yes,  I have run this script and it works OK.
Device Tesla V100-PCIE-32GB
***FP16 Gemm Testing***

-----------------------------
GEMM test 0: [M: 128, K: 768, N: 768] from_tensor * weightQ/K/V, attr * output_kernel
algo_99 costs 0.015ms
algo_100 costs 0.016ms
algo_101 costs 0.020ms

**Comment by dontloo** [comment]
@zhoushan2186new  so does that solve your problem or you still have the same problem?

**Comment by dontloo** [comment]
@zhoushan2186new it looks like a problem with cublas gemm algorithm configuration, if you still have the problem could you provide the `gemm_config.in` under your **working directory**?

**Comment by zhoushan2186new** [comment]
Here is the content from gemm_config.in，I run the script like this "./gemm_fp16 1 128 12 64"
107
101
109
107
107
And the bert mode is from google/bert base model "uncased_L-12_H-768_A-12.zip". 
Details from bert_config.json shows like this:
{
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "type_vocab_size": 2,
  "vocab_size": 30522
}
~

**Comment by zhoushan2186new** [comment]
@dontloo And the issue still exists after checking the info you have mentioned.

**Comment by IrishCoffee** [comment]
You are using Tensorflow 1.14 with cuda10.1?

We can only support Tensorflow 1.13 with cuda10.0.

**Comment by dontloo** [comment]
@zhoushan2186new  hi thanks for the information, however I could not reproduce your error on my environment, could you try Tensorflow 1.13 with cuda10.0 as mentioned by IrishCoffee?

**Comment by zhoushan2186new** [comment]
@IrishCoffee @dontloo, Thanks for  your help. What I  am using  is CUDA10.0.130+Tensorflow1.13.1
Is there any docker image I can download to try?

**Comment by zhoushan2186new** [comment]
@IrishCoffee @dontloo, I change the docker to nvcr.io/nvidia/tensorflow:19.02-py3. It works now.
Thanks again. Before that what I use is cuda-devel docker although cuda and tf verison is right, but i guess there is other problem about the environment.
