### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by shradda8** [NVIDIA/DeepLearningExamples#308]
**encountering cuda runtime error** 
File "/workspace/tacotron2/tacotron2/data_function.py", line 148, in batch_to_gpu
    max_len = torch.max(input_lengths.data).item()
RuntimeError: cuda runtime error (209) : no kernel image is available for execution on the device at /tmp/pip-req-build-akjifb_7/aten/src/THC/generic/THCTensorMathReduce.cu:94

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.50       Driver Version: 430.50       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 0000E5F5:00:00.0 Off |                    0 |
| N/A   50C    P0    59W / 149W |      0MiB / 11441MiB |     97%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

![image](https://user-images.githubusercontent.com/57967822/69191875-63717f00-0af1-11ea-8cc2-9737c5943ab8.png)

**Comment by Montantes** [comment]
What is your environment? What os? What version? Did you try to remove, and reinstall NVIDIA Driver? If linux you can try` $ Nvidia-bug-report.sh` ? 

Maybe it can help. https://blog.exxactcorp.com/gather-export-nvidia-bug-report-logs/

**Comment by shradda8** [comment]
I am using ubuntu 18.04. 
Yes, I had Nvidia 390 and reinstalled it to upgrade to 430.

**Comment by shradda8** [comment]
Also, my system CUDA version shows 9.1 even after upgrading it to 10.1 and inside the docker it shows 10.1.

:::NVLOGv0.2.2 Tacotron2_PyT 1574258183.811701536 (/workspace/tacotron2/dllogger/logger.py:251) train_loop
:::NVLOGv0.2.2 Tacotron2_PyT 1574258183.812253237 (/workspace/tacotron2/dllogger/logger.py:251) train_epoch_start: 0
Batch: 0/97 epoch 0
:::NVLOGv0.2.2 Tacotron2_PyT 1574258187.194901943 (/workspace/tacotron2/dllogger/logger.py:251) train_iter_start: 0
THCudaCheck FAIL file=/tmp/pip-req-build-akjifb_7/aten/src/THC/generic/THCTensorMathReduce.cu line=94 error=209 : no kernel image is available for execution on the device
Traceback (most recent call last):
  File "train.py", line 501, in <module>
    main()
  File "train.py", line 411, in main
    x, y, num_items = batch_to_gpu(batch)
  File "/workspace/tacotron2/tacotron2/data_function.py", line 148, in batch_to_gpu
    max_len = torch.max(input_lengths.data).item()
RuntimeError: cuda runtime error (209) : no kernel image is available for execution on the device at /tmp/pip-req-build-akjifb_7/aten/src/THC/generic/THCTensorMathReduce.cu:94

**Comment by GrzegorzKarchNV** [comment]
You get the error because Tesla K80 has compute capability 3.7 which might be unsupported by PyTorch. What you could try is install PyTorch from source.

**Comment by shradda8** [comment]
@GrzegorzKarchNV 
Could you please instruct on getting PyTorch from source

**Comment by GrzegorzKarchNV** [comment]
here you go: https://github.com/pytorch/pytorch#from-source

**Comment by shradda8** [comment]
@GrzegorzKarchNV thanks a lot!

**Comment by shradda8** [comment]
@GrzegorzKarchNV @Montantes @swarren @aaronp24   I have the same error even after installing PyTorch from source.
are there any other work arounds. Please help!

**Comment by shradda8** [comment]
do I need to change/edit the docker file

**Comment by fosimoes** [comment]
I am stuck with same problem, did anyone find a workaround?
Installing Pytorch from source did not help.
As far as I have checked, the docker image (pytorch:19.10-py3) is compatible with my system settings:
Ubuntu 18.04, 
NVIDIA-SMI 418.87.01    Driver Version: 418.87.01    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 00000000:00:04.0 Off |                    0 |
| N/A   30C    P8    28W / 149W |      0MiB / 11441MiB |      0%      Default |

**Comment by GrzegorzKarchNV** [comment]
I'm trying to figure out why you get this error; in the meantime, @shradda8 could you post your training command and the whole error log from your training?

**Comment by fosimoes** [comment]
Updating my previous post: a second attempt to install PyTorch from source worked for me!

**Comment by shradda8** [comment]
@fosimoes could you please tell me how you made it work

**Comment by shradda8** [comment]
@GrzegorzKarchNV  @fosimoes  Below is the output log for the command: bash scripts/train_tacotron2.sh



:::NVLOGv0.2.2 Tacotron2_PyT 1575262076.214365721 (/workspace/tacotron2/dllogger/logger.py:279) run_start
:::NVLOGv0.2.2 Tacotron2_PyT 1575262076.221471071 (/workspace/tacotron2/dllogger/logger.py:251) cpu_info: {"num": 6, "name": "Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz"}
:::NVLOGv0.2.2 Tacotron2_PyT 1575262076.227468491 (/workspace/tacotron2/dllogger/logger.py:251) mem_info: {"ram": "55G"}
:::NVLOGv0.2.2 Tacotron2_PyT 1575262076.278186321 (/workspace/tacotron2/dllogger/logger.py:251) gpu_info: {"driver_version": "440.33.01", "num": 1, "name": ["Tesla K80"], "mem": ["11441 MiB"]}
:::NVLOGv0.2.2 Tacotron2_PyT 1575262076.281424522 (/workspace/tacotron2/dllogger/logger.py:251) args: {"output_directory": "./output/", "dataset_path": "./", "model_name": "Tacotron2", "log_file": "./output/nvlog.json", "anneal_steps": ["500", "1000", "1500"], "anneal_factor": 0.1, "epochs": 1501, "epochs_per_checkpoint": 50, "checkpoint_path": "", "seed": 1234, "dynamic_loss_scaling": true, "amp_run": true, "cudnn_enabled": true, "cudnn_benchmark": false, "disable_uniform_initialize_bn_weight": false, "use_saved_learning_rate": false, "learning_rate": 0.001, "weight_decay": 1e-06, "grad_clip_thresh": 1.0, "batch_size": 128, "grad_clip": 5.0, "load_mel_from_disk": false, "training_files": "filelists/ljs_audio_text_train_filelist.txt", "validation_files": "filelists/ljs_audio_text_val_filelist.txt", "text_cleaners": ["english_cleaners"], "max_wav_value": 32768.0, "sampling_rate": 22050, "filter_length": 1024, "hop_length": 256, "win_length": 1024, "mel_fmin": 0.0, "mel_fmax": 8000.0, "rank": 0, "world_size": 1, "dist_url": "tcp://localhost:23456", "group_name": "group_name", "dist_backend": "nccl", "mask_padding": false, "n_mel_channels": 80, "n_symbols": 148, "symbols_embedding_dim": 512, "encoder_kernel_size": 5, "encoder_n_convolutions": 3, "encoder_embedding_dim": 512, "n_frames_per_step": 1, "decoder_rnn_dim": 1024, "prenet_dim": 256, "max_decoder_steps": 2000, "gate_threshold": 0.5, "p_attention_dropout": 0.1, "p_decoder_dropout": 0.1, "decoder_no_early_stopping": false, "attention_rnn_dim": 1024, "attention_dim": 128, "attention_location_n_filters": 32, "attention_location_kernel_size": 31, "postnet_embedding_dim": 512, "postnet_kernel_size": 5, "postnet_n_convolutions": 5}
:::NVLOGv0.2.2 Tacotron2_PyT 1575262076.281892776 (/workspace/tacotron2/dllogger/logger.py:251) run_start
Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
:::NVLOGv0.2.2 Tacotron2_PyT 1575262077.954160452 (/workspace/tacotron2/dllogger/logger.py:251) train_loop
:::NVLOGv0.2.2 Tacotron2_PyT 1575262077.954715967 (/workspace/tacotron2/dllogger/logger.py:251) train_epoch_start: 0
Batch: 0/97 epoch 0
:::NVLOGv0.2.2 Tacotron2_PyT 1575262081.420332909 (/workspace/tacotron2/dllogger/logger.py:251) train_iter_start: 0
THCudaCheck FAIL file=/tmp/pip-req-build-akjifb_7/aten/src/THC/generic/THCTensorMathReduce.cu line=94 error=209 : no kernel image is available for execution on the device
Traceback (most recent call last):
  File "train.py", line 501, in <module>
    main()
  File "train.py", line 411, in main
    x, y, num_items = batch_to_gpu(batch)
  File "/workspace/tacotron2/tacotron2/data_function.py", line 148, in batch_to_gpu
    max_len = torch.max(input_lengths.data).item()
RuntimeError: cuda runtime error (209) : no kernel image is available for execution on the device at /tmp/pip-req-build-akjifb_7/aten/src/THC/generic/THCTensorMathReduce.cu:94

**Comment by fosimoes** [comment]
I modified the dockerfile in order to include Pytorch installation from source.
Here is the modified dockerfile that worked for me:

FROM nvcr.io/nvidia/pytorch:19.10-py3

#Install pytorch from source
WORKDIR /workspace
RUN git clone --recursive https://github.com/pytorch/pytorch
WORKDIR /workspace/pytorch
RUN git submodule sync
RUN git submodule update --init --recursive
RUN export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
RUN python setup.py install

ADD . /workspace/tacotron2
WORKDIR /workspace/tacotron2
RUN pip install -r requirements.txt

**Comment by GrzegorzKarchNV** [comment]
FYI, it seems that a similar  issue has been discussed here: https://github.com/NVIDIA/flownet2-pytorch/issues/86

**Comment by shradda8** [comment]
@GrzegorzKarchNV @fosimoes 
thank you. i do not see that error anymore

**Comment by GrzegorzKarchNV** [comment]
@shradda8 how did you solve the issue eventually?

**Comment by shradda8** [comment]
@GrzegorzKarchNV  The edited dockerfile to install pytorch from source helped. However, I ran into memory issue later but fixed it by reducing the batch size

**Comment by GrzegorzKarchNV** [comment]
got it, thanks!
