### ISSUE TITLE
[BERT/TF] Multi-node SQUAD fine tuning hangs

### ISSUE THREAD

**Issue by changlan** [NVIDIA/DeepLearningExamples#383]
### Environment
1. TensorFlow 1.15
2. Horovod 0.18.1
3. OpenMPI 4.0
4. CUDA 10.0
5. NCCL 2.4.8
6. Python 3.5

### Issue 
I tried to run multi-node SQUAD fine tuning on two VMs (each with 8 * V100) using the following command:
```
mpirun -np 16 -hostfile HOSTFILE -mca plm_rsh_no_tree_spawn 1 -bind-to socket -map-by slot -x NCCL_MIN_NRINGS=4 -x TF_CPP_MIN_LOG_LEVEL=0 -x NCCL_DEBUG=INFO -x -x NCCL_ALGO=Ring -x NCCL_BUFFSIZE=8388608 -mca pml ob1 -mca btl ^openib -mca btl_tcp_if_exclude lo,docker0 python3 DeepLearningExamples/TensorFlow/LanguageModeling/BERT/run_squad.py --vocab_file=DeepLearningExamples/TensorFlow/LanguageModeling/BERT/data/download/google_pretrained_weights/uncased_L-24_H-1024_A-16/vocab.txt --bert_config_file=DeepLearningExamples/TensorFlow/LanguageModeling/BERT/data/download/google_pretrained_weights/uncased_L-24_H-1024_A-16/bert_config.json --init_checkpoint=DeepLearningExamples/TensorFlow/LanguageModeling/BERT/data/download/google_pretrained_weights/uncased_L-24_H-1024_A-16/bert_model.ckpt --do_train=True --train_file=DeepLearningExamples/TensorFlow/LanguageModeling/BERT/data/download/squad/v1.1/train-v1.1.json --train_batch_size=2 --learning_rate=5e-6 --num_train_epochs=1 --max_seq_length=128 --doc_stride=128 --output_dir=/tmp/pkb --horovod --use_fp16
```

However, the master rank (rank 0) hangs with the following message (actually the iteration was not completely stalled. It progressed very slowly):
```
2020-01-23 23:25:03.863322: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-01-23 23:25:03.928604: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-01-23 23:25:03.940879: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-01-23 23:25:04.633817: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-01-23 23:25:04.872561: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-01-23 23:25:04.924935: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-01-23 23:25:05.165986: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-01-23 23:25:05.313782: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
[2020-01-23 23:26:23. 26353: W horovod/common/stall_inspector.cc:105] One or more tensors were submitted to be reduced, gathered or broadcasted by
 subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit diff
erent tensors or that only subset of ranks is submitting tensors, which will cause deadlock. 
Stalled ranks:
8: [DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1000_0, DistributedAdamWeigh
tDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1003_0, DistributedAdamWeightDecayOptimizer_Allreduc
e/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1006_0, DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_Distr
ibutedAdamWeightDecayOptimizer_Allreduce_Cast_1009_0, DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOpt
imizer_Allreduce_Cast_100_0, DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_101
2_0 ...]
9: [DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1000_0, DistributedAdamWeigh
tDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1003_0, DistributedAdamWeightDecayOptimizer_Allreduc
e/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1006_0, DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_Distr
ibutedAdamWeightDecayOptimizer_Allreduce_Cast_1009_0, DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOpt
imizer_Allreduce_Cast_100_0, DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_101
2_0 ...]
10: [DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1000_0, DistributedAdamWeig
htDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1003_0, DistributedAdamWeightDecayOptimizer_Allredu
ce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1006_0, DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_Dist
ributedAdamWeightDecayOptimizer_Allreduce_Cast_1009_0, DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOp
timizer_Allreduce_Cast_100_0, DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_10
12_0 ...]
11: [DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1000_0, DistributedAdamWeig
htDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1003_0, DistributedAdamWeightDecayOptimizer_Allredu
ce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1006_0, DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_Dist
ributedAdamWeightDecayOptimizer_Allreduce_Cast_1009_0, DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOp
timizer_Allreduce_Cast_100_0, DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_10
12_0 ...]
12: [DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1000_0, DistributedAdamWeig
htDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1003_0, DistributedAdamWeightDecayOptimizer_Allredu
ce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1006_0, DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_Dist
ributedAdamWeightDecayOptimizer_Allreduce_Cast_1009_0, DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOp
timizer_Allreduce_Cast_100_0, DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_10
12_0 ...]
13: [DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1000_0, DistributedAdamWeig
htDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1003_0, DistributedAdamWeightDecayOptimizer_Allredu
ce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1006_0, DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_Dist
ributedAdamWeightDecayOptimizer_Allreduce_Cast_1009_0, DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOp
timizer_Allreduce_Cast_100_0, DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_10
12_0 ...]
14: [DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1000_0, DistributedAdamWeig
htDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1003_0, DistributedAdamWeightDecayOptimizer_Allredu
ce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1006_0, DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_Dist
ributedAdamWeightDecayOptimizer_Allreduce_Cast_1009_0, DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOp
timizer_Allreduce_Cast_100_0, DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_10
12_0 ...]
15: [DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1000_0, DistributedAdamWeig
htDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1003_0, DistributedAdamWeightDecayOptimizer_Allredu
ce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1006_0, DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_Dist
ributedAdamWeightDecayOptimizer_Allreduce_Cast_1009_0, DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOp
timizer_Allreduce_Cast_100_0, DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_10
12_0 ...]
```

I also tested on the single node with 8 GPUs. It worked without any issues.

**Comment by swethmandava** [comment]
Please refer to these [instructions](https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow/LanguageModeling/BERT#multi-node) to run BERT TF on multiple nodes.

**Comment by changlan** [comment]
AFAIK the instruction is for pretraining. Just to confirm: does run_squad.py not support multi-node training?

**Comment by swethmandava** [comment]
run_squad.py also supports multinode. The setup process for multimode for both finetuning and pretraining is similar.

Just to confirm: are you able to run pretraining with multinode? Did you test your MPI setup with a simpler application?

**Comment by changlan** [comment]
Thanks for the info. I didn't try pretraining because I did not have enough space for training data in my setup. However, I did try TF ResNet in this code repo with multi-node and it worked without issue.

**Comment by changlan** [comment]
Hi @swethmandava, is there any blocker for taking PR #386?

**Comment by swethmandava** [comment]
hi @changlan, there are a couple of issues with your PR
1. you are not utilizing all the gpus to preprocess 
2. [This line](https://github.com/NVIDIA/DeepLearningExamples/blob/0845aaa90187e0b79d244648deb2c9656bd6fb66/TensorFlow/LanguageModeling/BERT/run_squad.py#L403) is sharding the files between gpus. Having only one file beats the purpose.

**Comment by changlan** [comment]
My understanding is that `convert_examples_to_features` is done on CPUs, and `TFRecordDataset.shard()` shards the **dataset**, not **files**. If there is one file, it still includes `1/num_shards` samples in the file.

https://www.tensorflow.org/api_docs/python/tf/data/TFRecordDataset#shard

**Comment by vilmara** [comment]
Hi @swethmandava / @changlan, how did you fix this issue?, I am seeing the same error, my multi-node system (8 gpu's in total) hangs when running [BERT/TF] Multi-node SQUAD fine-tuning. I know my SW configuration is fine since I was able to run pre-training on multi-node without issues. 

It seems that the stalled ranks are on node 2 (GPUs 4,5,6, and 7). See below the error of multinode fine-tune:
```
node-1:32726:33054 [0] NCCL INFO NCCL_SOCKET_IFNAME set to ib0
node-1:32726:33054 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
node-1:32726:33054 [0] NCCL INFO NCCL_IB_DISABLE set by environment to 0.
node-1:32726:33054 [0] NCCL INFO NCCL_SOCKET_IFNAME set to ib0
node-1:32726:33054 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB ib0:192.168.11.1<0>
NCCL version 2.7.5+cuda11.0
node-1:32728:33057 [2] NCCL INFO NCCL_SOCKET_IFNAME set to ib0
node-1:32729:33061 [3] NCCL INFO NCCL_SOCKET_IFNAME set to ib0
node-1:32728:33057 [2] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
node-1:32727:33064 [1] NCCL INFO NCCL_SOCKET_IFNAME set to ib0
node-1:32728:33057 [2] NCCL INFO NCCL_IB_DISABLE set by environment to 0.
node-1:32728:33057 [2] NCCL INFO NCCL_SOCKET_IFNAME set to ib0
node-1:32727:33064 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
node-1:32729:33061 [3] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
node-1:32727:33064 [1] NCCL INFO NCCL_IB_DISABLE set by environment to 0.
node-1:32727:33064 [1] NCCL INFO NCCL_SOCKET_IFNAME set to ib0
node-1:32729:33061 [3] NCCL INFO NCCL_IB_DISABLE set by environment to 0.
node-1:32729:33061 [3] NCCL INFO NCCL_SOCKET_IFNAME set to ib0
node-1:32728:33057 [2] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB ib0:192.168.11.1<0>
node-1:32727:33064 [1] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB ib0:192.168.11.1<0>
node-1:32729:33061 [3] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB ib0:192.168.11.1<0>
node-2:38143:38660 [3] NCCL INFO NCCL_SOCKET_IFNAME set to ib0
node-2:38143:38660 [3] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
node-2:38143:38660 [3] NCCL INFO NCCL_IB_DISABLE set by environment to 0.
node-2:38143:38660 [3] NCCL INFO NCCL_SOCKET_IFNAME set to ib0
node-2:38142:38664 [2] NCCL INFO NCCL_SOCKET_IFNAME set to ib0
node-2:38141:38665 [1] NCCL INFO NCCL_SOCKET_IFNAME set to ib0
node-2:38140:38663 [0] NCCL INFO NCCL_SOCKET_IFNAME set to ib0
node-2:38142:38664 [2] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
node-2:38142:38664 [2] NCCL INFO NCCL_IB_DISABLE set by environment to 0.
node-2:38142:38664 [2] NCCL INFO NCCL_SOCKET_IFNAME set to ib0
node-2:38141:38665 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
node-2:38140:38663 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
node-2:38141:38665 [1] NCCL INFO NCCL_IB_DISABLE set by environment to 0.
node-2:38141:38665 [1] NCCL INFO NCCL_SOCKET_IFNAME set to ib0
node-2:38140:38663 [0] NCCL INFO NCCL_IB_DISABLE set by environment to 0.
node-2:38140:38663 [0] NCCL INFO NCCL_SOCKET_IFNAME set to ib0
node-2:38140:38663 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB ib0:192.168.11.2<0>
node-2:38142:38664 [2] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB ib0:192.168.11.2<0>
node-2:38141:38665 [1] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB ib0:192.168.11.2<0>
node-2:38143:38660 [3] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB ib0:192.168.11.2<0>
node-1:32728:33057 [2] NCCL INFO NET/IB: Dev 0 Port 1 qpn 1656 mtu 5 LID 1
node-1:32726:33054 [0] NCCL INFO NET/IB: Dev 0 Port 1 qpn 1659 mtu 5 LID 1
node-1:32727:33064 [1] NCCL INFO NET/IB: Dev 0 Port 1 qpn 1658 mtu 5 LID 1
node-1:32729:33061 [3] NCCL INFO NET/IB: Dev 0 Port 1 qpn 1657 mtu 5 LID 1
node-2:38140:38663 [0] NCCL INFO NET/IB: Dev 0 Port 1 qpn 2010 mtu 5 LID 4
node-2:38142:38664 [2] NCCL INFO NET/IB: Dev 0 Port 1 qpn 2013 mtu 5 LID 4
node-2:38141:38665 [1] NCCL INFO NET/IB: Dev 0 Port 1 qpn 2012 mtu 5 LID 4
node-2:38143:38660 [3] NCCL INFO NET/IB: Dev 0 Port 1 qpn 2011 mtu 5 LID 4
node-1:32728:33057 [2] NCCL INFO NCCL_NET_GDR_LEVEL set by environment to PHB
node-1:32728:33057 [2] NCCL INFO GPU Direct RDMA Disabled for GPU 18000 / HCA 0 (distance 5 > 4)
node-1:32728:33057 [2] NCCL INFO GPU Direct RDMA Disabled for GPU 3b000 / HCA 0 (distance 5 > 4)
node-1:32728:33057 [2] NCCL INFO GPU Direct RDMA Enabled for GPU 86000 / HCA 0 (distance 4 <= 4), read 0
node-1:32728:33057 [2] NCCL INFO GPU Direct RDMA Enabled for GPU af000 / HCA 0 (distance 4 <= 4), read 0
node-1:32728:33057 [2] NCCL INFO GPU Direct RDMA Disabled for GPU 18000 / HCA 0 (distance 5 > 4)
node-1:32728:33057 [2] NCCL INFO GPU Direct RDMA Disabled for GPU 3b000 / HCA 0 (distance 5 > 4)
node-1:32728:33057 [2] NCCL INFO GPU Direct RDMA Enabled for GPU 86000 / HCA 0 (distance 4 <= 4), read 0
node-1:32728:33057 [2] NCCL INFO GPU Direct RDMA Enabled for GPU af000 / HCA 0 (distance 4 <= 4), read 0
node-1:32729:33061 [3] NCCL INFO NCCL_NET_GDR_LEVEL set by environment to PHB
node-1:32729:33061 [3] NCCL INFO GPU Direct RDMA Disabled for GPU 18000 / HCA 0 (distance 5 > 4)
node-1:32729:33061 [3] NCCL INFO GPU Direct RDMA Disabled for GPU 3b000 / HCA 0 (distance 5 > 4)
node-1:32729:33061 [3] NCCL INFO GPU Direct RDMA Enabled for GPU 86000 / HCA 0 (distance 4 <= 4), read 0
node-1:32729:33061 [3] NCCL INFO GPU Direct RDMA Enabled for GPU af000 / HCA 0 (distance 4 <= 4), read 0
node-1:32729:33061 [3] NCCL INFO GPU Direct RDMA Disabled for GPU 18000 / HCA 0 (distance 5 > 4)
node-1:32729:33061 [3] NCCL INFO GPU Direct RDMA Disabled for GPU 3b000 / HCA 0 (distance 5 > 4)
node-1:32729:33061 [3] NCCL INFO GPU Direct RDMA Enabled for GPU 86000 / HCA 0 (distance 4 <= 4), read 0
node-1:32729:33061 [3] NCCL INFO GPU Direct RDMA Enabled for GPU af000 / HCA 0 (distance 4 <= 4), read 0
node-1:32726:33054 [0] NCCL INFO NCCL_NET_GDR_LEVEL set by environment to PHB
node-1:32726:33054 [0] NCCL INFO GPU Direct RDMA Disabled for GPU 18000 / HCA 0 (distance 5 > 4)
node-1:32726:33054 [0] NCCL INFO GPU Direct RDMA Disabled for GPU 3b000 / HCA 0 (distance 5 > 4)
node-1:32726:33054 [0] NCCL INFO GPU Direct RDMA Enabled for GPU 86000 / HCA 0 (distance 4 <= 4), read 0
node-1:32726:33054 [0] NCCL INFO GPU Direct RDMA Enabled for GPU af000 / HCA 0 (distance 4 <= 4), read 0
node-1:32726:33054 [0] NCCL INFO GPU Direct RDMA Disabled for GPU 18000 / HCA 0 (distance 5 > 4)
node-1:32726:33054 [0] NCCL INFO GPU Direct RDMA Disabled for GPU 3b000 / HCA 0 (distance 5 > 4)
node-1:32726:33054 [0] NCCL INFO GPU Direct RDMA Enabled for GPU 86000 / HCA 0 (distance 4 <= 4), read 0
node-1:32726:33054 [0] NCCL INFO GPU Direct RDMA Enabled for GPU af000 / HCA 0 (distance 4 <= 4), read 0
node-1:32727:33064 [1] NCCL INFO NCCL_NET_GDR_LEVEL set by environment to PHB
node-1:32727:33064 [1] NCCL INFO GPU Direct RDMA Disabled for GPU 18000 / HCA 0 (distance 5 > 4)
node-1:32727:33064 [1] NCCL INFO GPU Direct RDMA Disabled for GPU 3b000 / HCA 0 (distance 5 > 4)
node-1:32727:33064 [1] NCCL INFO GPU Direct RDMA Enabled for GPU 86000 / HCA 0 (distance 4 <= 4), read 0
node-1:32727:33064 [1] NCCL INFO GPU Direct RDMA Enabled for GPU af000 / HCA 0 (distance 4 <= 4), read 0
node-1:32727:33064 [1] NCCL INFO GPU Direct RDMA Disabled for GPU 18000 / HCA 0 (distance 5 > 4)
node-1:32727:33064 [1] NCCL INFO GPU Direct RDMA Disabled for GPU 3b000 / HCA 0 (distance 5 > 4)
node-1:32727:33064 [1] NCCL INFO GPU Direct RDMA Enabled for GPU 86000 / HCA 0 (distance 4 <= 4), read 0
node-1:32727:33064 [1] NCCL INFO GPU Direct RDMA Enabled for GPU af000 / HCA 0 (distance 4 <= 4), read 0
node-2:38143:38660 [3] NCCL INFO NCCL_NET_GDR_LEVEL set by environment to PHB
node-2:38143:38660 [3] NCCL INFO GPU Direct RDMA Disabled for GPU 18000 / HCA 0 (distance 5 > 4)
node-2:38143:38660 [3] NCCL INFO GPU Direct RDMA Disabled for GPU 3b000 / HCA 0 (distance 5 > 4)
node-2:38143:38660 [3] NCCL INFO GPU Direct RDMA Enabled for GPU 86000 / HCA 0 (distance 4 <= 4), read 0
node-2:38143:38660 [3] NCCL INFO GPU Direct RDMA Enabled for GPU af000 / HCA 0 (distance 4 <= 4), read 0
node-2:38143:38660 [3] NCCL INFO GPU Direct RDMA Disabled for GPU 18000 / HCA 0 (distance 5 > 4)
node-2:38143:38660 [3] NCCL INFO GPU Direct RDMA Disabled for GPU 3b000 / HCA 0 (distance 5 > 4)
node-2:38143:38660 [3] NCCL INFO GPU Direct RDMA Enabled for GPU 86000 / HCA 0 (distance 4 <= 4), read 0
node-2:38143:38660 [3] NCCL INFO GPU Direct RDMA Enabled for GPU af000 / HCA 0 (distance 4 <= 4), read 0
node-2:38142:38664 [2] NCCL INFO NCCL_NET_GDR_LEVEL set by environment to PHB
node-2:38142:38664 [2] NCCL INFO GPU Direct RDMA Disabled for GPU 18000 / HCA 0 (distance 5 > 4)
node-2:38142:38664 [2] NCCL INFO GPU Direct RDMA Disabled for GPU 3b000 / HCA 0 (distance 5 > 4)
node-2:38142:38664 [2] NCCL INFO GPU Direct RDMA Enabled for GPU 86000 / HCA 0 (distance 4 <= 4), read 0
node-2:38142:38664 [2] NCCL INFO GPU Direct RDMA Enabled for GPU af000 / HCA 0 (distance 4 <= 4), read 0
node-2:38142:38664 [2] NCCL INFO GPU Direct RDMA Disabled for GPU 18000 / HCA 0 (distance 5 > 4)
node-2:38142:38664 [2] NCCL INFO GPU Direct RDMA Disabled for GPU 3b000 / HCA 0 (distance 5 > 4)
node-2:38142:38664 [2] NCCL INFO GPU Direct RDMA Enabled for GPU 86000 / HCA 0 (distance 4 <= 4), read 0
node-2:38142:38664 [2] NCCL INFO GPU Direct RDMA Enabled for GPU af000 / HCA 0 (distance 4 <= 4), read 0
node-2:38141:38665 [1] NCCL INFO NCCL_NET_GDR_LEVEL set by environment to PHB
node-2:38141:38665 [1] NCCL INFO GPU Direct RDMA Disabled for GPU 18000 / HCA 0 (distance 5 > 4)
node-2:38141:38665 [1] NCCL INFO GPU Direct RDMA Disabled for GPU 3b000 / HCA 0 (distance 5 > 4)
node-2:38141:38665 [1] NCCL INFO GPU Direct RDMA Enabled for GPU 86000 / HCA 0 (distance 4 <= 4), read 0
node-2:38141:38665 [1] NCCL INFO GPU Direct RDMA Enabled for GPU af000 / HCA 0 (distance 4 <= 4), read 0
node-2:38141:38665 [1] NCCL INFO GPU Direct RDMA Disabled for GPU 18000 / HCA 0 (distance 5 > 4)
node-2:38141:38665 [1] NCCL INFO GPU Direct RDMA Disabled for GPU 3b000 / HCA 0 (distance 5 > 4)
node-2:38141:38665 [1] NCCL INFO GPU Direct RDMA Enabled for GPU 86000 / HCA 0 (distance 4 <= 4), read 0
node-2:38141:38665 [1] NCCL INFO GPU Direct RDMA Enabled for GPU af000 / HCA 0 (distance 4 <= 4), read 0
node-2:38140:38663 [0] NCCL INFO NCCL_NET_GDR_LEVEL set by environment to PHB
node-2:38140:38663 [0] NCCL INFO GPU Direct RDMA Disabled for GPU 18000 / HCA 0 (distance 5 > 4)
node-2:38140:38663 [0] NCCL INFO GPU Direct RDMA Disabled for GPU 3b000 / HCA 0 (distance 5 > 4)
node-2:38140:38663 [0] NCCL INFO GPU Direct RDMA Enabled for GPU 86000 / HCA 0 (distance 4 <= 4), read 0
node-2:38140:38663 [0] NCCL INFO GPU Direct RDMA Enabled for GPU af000 / HCA 0 (distance 4 <= 4), read 0
node-2:38140:38663 [0] NCCL INFO GPU Direct RDMA Disabled for GPU 18000 / HCA 0 (distance 5 > 4)
node-2:38140:38663 [0] NCCL INFO GPU Direct RDMA Disabled for GPU 3b000 / HCA 0 (distance 5 > 4)
node-2:38140:38663 [0] NCCL INFO GPU Direct RDMA Enabled for GPU 86000 / HCA 0 (distance 4 <= 4), read 0
node-2:38140:38663 [0] NCCL INFO GPU Direct RDMA Enabled for GPU af000 / HCA 0 (distance 4 <= 4), read 0
node-1:32728:33057 [2] NCCL INFO GPU Direct RDMA Enabled for GPU 86000 / HCA 0 (distance 4 <= 4), read 0
node-2:38142:38664 [2] NCCL INFO GPU Direct RDMA Enabled for GPU 86000 / HCA 0 (distance 4 <= 4), read 0
node-1:32728:33057 [2] NCCL INFO Channel 00 : 7[af000] -> 2[86000] [receive] via NET/IB/0/GDRDMA
node-1:32729:33061 [3] NCCL INFO GPU Direct RDMA Enabled for GPU af000 / HCA 0 (distance 4 <= 4), read 1
node-1:32729:33061 [3] NCCL INFO Channel 00 : 3[af000] -> 6[86000] [send] via NET/IB/0/GDRDMA
node-2:38142:38664 [2] NCCL INFO Channel 00 : 3[af000] -> 6[86000] [receive] via NET/IB/0/GDRDMA
node-2:38143:38660 [3] NCCL INFO GPU Direct RDMA Enabled for GPU af000 / HCA 0 (distance 4 <= 4), read 1
node-1:32729:33061 [3] NCCL INFO NET/IB: Dev 0 Port 1 qpn 1668 mtu 5 LID 1
node-2:38143:38660 [3] NCCL INFO Channel 00 : 7[af000] -> 2[86000] [send] via NET/IB/0/GDRDMA
node-1:32729:33061 [3] NCCL INFO GPU Direct RDMA Enabled for GPU af000 / HCA 0 (distance 4 <= 4), read 0
node-1:32729:33061 [3] NCCL INFO Channel 00 : 6[86000] -> 3[af000] [receive] via NET/IB/0/GDRDMA
node-2:38143:38660 [3] NCCL INFO NET/IB: Dev 0 Port 1 qpn 2022 mtu 5 LID 4
node-2:38142:38664 [2] NCCL INFO GPU Direct RDMA Enabled for GPU 86000 / HCA 0 (distance 4 <= 4), read 1
node-2:38142:38664 [2] NCCL INFO Channel 00 : 6[86000] -> 3[af000] [send] via NET/IB/0/GDRDMA
node-2:38142:38664 [2] NCCL INFO NET/IB: Dev 0 Port 1 qpn 2025 mtu 5 LID 4
node-1:32728:33057 [2] NCCL INFO GPU Direct RDMA Enabled for GPU 86000 / HCA 0 (distance 4 <= 4), read 0
node-1:32728:33057 [2] NCCL INFO Channel 01 : 7[af000] -> 2[86000] [receive] via NET/IB/0/GDRDMA
node-1:32729:33061 [3] NCCL INFO GPU Direct RDMA Enabled for GPU af000 / HCA 0 (distance 4 <= 4), read 1
node-1:32729:33061 [3] NCCL INFO Channel 01 : 3[af000] -> 6[86000] [send] via NET/IB/0/GDRDMA
node-2:38142:38664 [2] NCCL INFO GPU Direct RDMA Enabled for GPU 86000 / HCA 0 (distance 4 <= 4), read 0
node-2:38142:38664 [2] NCCL INFO Channel 01 : 3[af000] -> 6[86000] [receive] via NET/IB/0/GDRDMA
node-2:38143:38660 [3] NCCL INFO GPU Direct RDMA Enabled for GPU af000 / HCA 0 (distance 4 <= 4), read 1
node-1:32729:33061 [3] NCCL INFO NET/IB: Dev 0 Port 1 qpn 1673 mtu 5 LID 1
node-2:38143:38660 [3] NCCL INFO Channel 01 : 7[af000] -> 2[86000] [send] via NET/IB/0/GDRDMA
node-2:38143:38660 [3] NCCL INFO NET/IB: Dev 0 Port 1 qpn 2026 mtu 5 LID 4
node-1:32728:33057 [2] NCCL INFO GPU Direct RDMA Enabled for GPU 86000 / HCA 0 (distance 4 <= 4), read 1
node-1:32728:33057 [2] NCCL INFO Channel 01 : 2[86000] -> 7[af000] [send] via NET/IB/0/GDRDMA
node-2:38143:38660 [3] NCCL INFO GPU Direct RDMA Enabled for GPU af000 / HCA 0 (distance 4 <= 4), read 0
node-2:38143:38660 [3] NCCL INFO Channel 01 : 2[86000] -> 7[af000] [receive] via NET/IB/0/GDRDMA
node-1:32728:33057 [2] NCCL INFO NET/IB: Dev 0 Port 1 qpn 1676 mtu 5 LID 1
WARNING:tensorflow:From /workspace/bert/utils/utils.py:47: The name tf.train.get_global_step is deprecated. Please use tf.compat.v1.train.get_global_step instead.

W0727 20:10:54.031119 140579789641536 module_wrapper.py:139] From /workspace/bert/utils/utils.py:47: The name tf.train.get_global_step is deprecated. Please use tf.com

WARNING:tensorflow:From /workspace/bert/utils/utils.py:47: The name tf.train.get_global_step is deprecated. Please use tf.compat.v1.train.get_global_step instead.

W0727 20:10:54.045791 139993335781184 module_wrapper.py:139] From /workspace/bert/utils/utils.py:47: The name tf.train.get_global_step is deprecated. Please use tf.com

WARNING:tensorflow:From /workspace/bert/utils/utils.py:47: The name tf.train.get_global_step is deprecated. Please use tf.compat.v1.train.get_global_step instead.

W0727 20:10:54.050501 139788582520640 module_wrapper.py:139] From /workspace/bert/utils/utils.py:47: The name tf.train.get_global_step is deprecated. Please use tf.com

WARNING:tensorflow:From /workspace/bert/utils/utils.py:47: The name tf.train.get_global_step is deprecated. Please use tf.compat.v1.train.get_global_step instead.

W0727 20:10:54.049406 139944258537280 module_wrapper.py:139] From /workspace/bert/utils/utils.py:47: The name tf.train.get_global_step is deprecated. Please use tf.com

WARNING:tensorflow:From /workspace/bert/utils/utils.py:47: The name tf.train.get_global_step is deprecated. Please use tf.compat.v1.train.get_global_step instead.

W0727 20:10:54.051732 139669427681088 module_wrapper.py:139] From /workspace/bert/utils/utils.py:47: The name tf.train.get_global_step is deprecated. Please use tf.com

WARNING:tensorflow:From /workspace/bert/utils/utils.py:47: The name tf.train.get_global_step is deprecated. Please use tf.compat.v1.train.get_global_step instead.

W0727 20:10:54.065497 140204043544384 module_wrapper.py:139] From /workspace/bert/utils/utils.py:47: The name tf.train.get_global_step is deprecated. Please use tf.com

WARNING:tensorflow:From /workspace/bert/utils/utils.py:47: The name tf.train.get_global_step is deprecated. Please use tf.compat.v1.train.get_global_step instead.

W0727 20:10:54.095698 140135982995264 module_wrapper.py:139] From /workspace/bert/utils/utils.py:47: The name tf.train.get_global_step is deprecated. Please use tf.com

WARNING:tensorflow:From /workspace/bert/utils/utils.py:47: The name tf.train.get_global_step is deprecated. Please use tf.compat.v1.train.get_global_step instead.

W0727 20:10:54.101364 140102330480448 module_wrapper.py:139] From /workspace/bert/utils/utils.py:47: The name tf.train.get_global_step is deprecated. Please use tf.com

2020-07-27 20:10:54.583696: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1987] Running auto_mixed_precision graph optimizer
2020-07-27 20:10:54.583970: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1343] No whitelist ops found, nothing to do
2020-07-27 20:10:54.649410: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1987] Running auto_mixed_precision graph optimizer
2020-07-27 20:10:54.649647: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1343] No whitelist ops found, nothing to do
2020-07-27 20:10:54.689543: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1987] Running auto_mixed_precision graph optimizer
2020-07-27 20:10:54.689814: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1343] No whitelist ops found, nothing to do
2020-07-27 20:10:54.697500: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1987] Running auto_mixed_precision graph optimizer
2020-07-27 20:10:54.697755: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1343] No whitelist ops found, nothing to do
2020-07-27 20:10:54.712092: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1987] Running auto_mixed_precision graph optimizer
2020-07-27 20:10:54.712367: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1343] No whitelist ops found, nothing to do
2020-07-27 20:10:54.734042: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1987] Running auto_mixed_precision graph optimizer
2020-07-27 20:10:54.734284: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1343] No whitelist ops found, nothing to do
2020-07-27 20:10:54.741925: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1987] Running auto_mixed_precision graph optimizer
2020-07-27 20:10:54.742143: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1343] No whitelist ops found, nothing to do
2020-07-27 20:10:54.770682: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1987] Running auto_mixed_precision graph optimizer
2020-07-27 20:10:54.770922: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1343] No whitelist ops found, nothing to do
2020-07-27 20:11:03.142006: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1987] Running auto_mixed_precision graph optimizer
2020-07-27 20:11:03.357104: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1035] Automatic Mixed Precision Grappler Pass Summary:

Total processable nodes: 29243
Recognized nodes available for conversion: 16565
Total nodes converted: 1157
Total FP16 Cast ops used (excluding Const and Variable casts): 195
Whitelisted nodes converted: 579
Blacklisted nodes blocking conversion: 1069
Nodes blocked from conversion by blacklisted nodes: 4484

For more information regarding mixed precision training, including how to make automatic mixed precision aware of a custom op type, please see the documentation availa
https://docs.nvidia.com/deeplearning/frameworks/tensorflow-user-guide/index.html#tfamp


2020-07-27 20:11:03.706669: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1987] Running auto_mixed_precision graph optimizer
2020-07-27 20:11:03.913584: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1035] Automatic Mixed Precision Grappler Pass Summary:

Total processable nodes: 29243
Recognized nodes available for conversion: 16565
Total nodes converted: 1157
Total FP16 Cast ops used (excluding Const and Variable casts): 195
Whitelisted nodes converted: 579
Blacklisted nodes blocking conversion: 1069
Nodes blocked from conversion by blacklisted nodes: 4484

For more information regarding mixed precision training, including how to make automatic mixed precision aware of a custom op type, please see the documentation availa
https://docs.nvidia.com/deeplearning/frameworks/tensorflow-user-guide/index.html#tfamp


2020-07-27 20:11:04.203149: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1987] Running auto_mixed_precision graph optimizer
2020-07-27 20:11:04.222833: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1987] Running auto_mixed_precision graph optimizer
2020-07-27 20:11:04.392173: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1987] Running auto_mixed_precision graph optimizer
2020-07-27 20:11:04.399945: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1035] Automatic Mixed Precision Grappler Pass Summary:

Total processable nodes: 29243
Recognized nodes available for conversion: 16565
Total nodes converted: 1157
Total FP16 Cast ops used (excluding Const and Variable casts): 195
Whitelisted nodes converted: 579
Blacklisted nodes blocking conversion: 1069
Nodes blocked from conversion by blacklisted nodes: 4484

For more information regarding mixed precision training, including how to make automatic mixed precision aware of a custom op type, please see the documentation availa
https://docs.nvidia.com/deeplearning/frameworks/tensorflow-user-guide/index.html#tfamp


2020-07-27 20:11:04.417132: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1035] Automatic Mixed Precision Grappler Pass Summary:

Total processable nodes: 29243
Recognized nodes available for conversion: 16565
Total nodes converted: 1157
Total FP16 Cast ops used (excluding Const and Variable casts): 195
Whitelisted nodes converted: 579
Blacklisted nodes blocking conversion: 1069
Nodes blocked from conversion by blacklisted nodes: 4484

For more information regarding mixed precision training, including how to make automatic mixed precision aware of a custom op type, please see the documentation availa
https://docs.nvidia.com/deeplearning/frameworks/tensorflow-user-guide/index.html#tfamp


2020-07-27 20:11:04.558607: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1035] Automatic Mixed Precision Grappler Pass Summary:

Total processable nodes: 29243
Recognized nodes available for conversion: 16565
Total nodes converted: 1157
Total FP16 Cast ops used (excluding Const and Variable casts): 195
Whitelisted nodes converted: 579
Blacklisted nodes blocking conversion: 1069
Nodes blocked from conversion by blacklisted nodes: 4484

For more information regarding mixed precision training, including how to make automatic mixed precision aware of a custom op type, please see the documentation availa
https://docs.nvidia.com/deeplearning/frameworks/tensorflow-user-guide/index.html#tfamp


2020-07-27 20:11:04.942616: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1987] Running auto_mixed_precision graph optimizer
2020-07-27 20:11:05.147107: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1035] Automatic Mixed Precision Grappler Pass Summary:

Total processable nodes: 29243
Recognized nodes available for conversion: 16565
Total nodes converted: 1157
Total FP16 Cast ops used (excluding Const and Variable casts): 195
Whitelisted nodes converted: 579
Blacklisted nodes blocking conversion: 1069
Nodes blocked from conversion by blacklisted nodes: 4484

For more information regarding mixed precision training, including how to make automatic mixed precision aware of a custom op type, please see the documentation availa
https://docs.nvidia.com/deeplearning/frameworks/tensorflow-user-guide/index.html#tfamp


2020-07-27 20:11:05.227239: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1987] Running auto_mixed_precision graph optimizer
2020-07-27 20:11:05.424763: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1035] Automatic Mixed Precision Grappler Pass Summary:

Total processable nodes: 29243
Recognized nodes available for conversion: 16565
Total nodes converted: 1157
Total FP16 Cast ops used (excluding Const and Variable casts): 195
Whitelisted nodes converted: 579
Blacklisted nodes blocking conversion: 1069
Nodes blocked from conversion by blacklisted nodes: 4484

For more information regarding mixed precision training, including how to make automatic mixed precision aware of a custom op type, please see the documentation availa
https://docs.nvidia.com/deeplearning/frameworks/tensorflow-user-guide/index.html#tfamp


2020-07-27 20:11:05.882269: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1987] Running auto_mixed_precision graph optimizer
2020-07-27 20:11:06.098792: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1035] Automatic Mixed Precision Grappler Pass Summary:

Total processable nodes: 29243
Recognized nodes available for conversion: 16565
Total nodes converted: 1157
Total FP16 Cast ops used (excluding Const and Variable casts): 195
Whitelisted nodes converted: 579
Blacklisted nodes blocking conversion: 1069
Nodes blocked from conversion by blacklisted nodes: 4484

For more information regarding mixed precision training, including how to make automatic mixed precision aware of a custom op type, please see the documentation availa
https://docs.nvidia.com/deeplearning/frameworks/tensorflow-user-guide/index.html#tfamp


2020-07-27 20:11:17.356538: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11
2020-07-27 20:11:17.780257: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11
2020-07-27 20:11:18.529565: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11
2020-07-27 20:11:20.315169: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11
[2020-07-27 20:13:10.546457: W horovod/common/stall_inspector.cc:105] One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and re than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause
Stalled ranks:
4: [DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1000_0, DistributedAdamWeightDecayOptimizer_AllrehtDecayOptimizer_Allreduce_Cast_1003_0, DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1006_0, DistrHorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1009_0, DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOpAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1012_0 ...]
5: [DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1000_0, DistributedAdamWeightDecayOptimizer_AllrehtDecayOptimizer_Allreduce_Cast_1003_0, DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1006_0, DistrHorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1009_0, DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOpAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1012_0 ...]
6: [DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1000_0, DistributedAdamWeightDecayOptimizer_AllrehtDecayOptimizer_Allreduce_Cast_1003_0, DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1006_0, DistrHorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1009_0, DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOpAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1012_0 ...]
7: [DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1000_0, DistributedAdamWeightDecayOptimizer_AllrehtDecayOptimizer_Allreduce_Cast_1003_0, DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1006_0, DistrHorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1009_0, DistributedAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOpAdamWeightDecayOptimizer_Allreduce/HorovodAllreduce_DistributedAdamWeightDecayOptimizer_Allreduce_Cast_1012_0 ...]
[2020-07-27 20:14:10.551108: W horovod/common/stall_inspector.cc:105] One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and re than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause

```

**Comment by changlan** [comment]
Hi @vilmara, PR #386 should be able to fix this issue. Please take a look.

@swethmandava, any blocker for taking the PR?

**Comment by vilmara** [comment]
Hi @changlan, it is working now. How long does it take to complete the fine-tuning process?

**Comment by changlan** [comment]
Good to know. Looks like this issue should remain open.

**Comment by vilmara** [comment]
@changlan what Accuracy Metric f1% did you get?
